[[constraint]]
  version = "v1.3.4"
  #branch = "master"
  name = "go.mongodb.org/mongo-driver"

[[constraint]]
  version = "v0.5.4"
  #branch = "master"
  name = "github.com/simagix/mongo-atlas"

[[constraint]]
  version = "v1.0.2"
  #branch = "dev"
  name = "github.com/simagix/mongo-ftdc"

[prune]
  go-tests = true
  unused-packages = true
